//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzabites.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string CUSEmail { get; set; }
        public string CUSName { get; set; }
        public string CUSPassword { get; set; }
        public string CUSContactNo { get; set; }
        public string CUSAddress { get; set; }
    }
}
